version: '3.2'

volumes:
  mariadb-data:

services:

#php slim rest
  backend:
    container_name: api-server
    depends_on:
      - database
    image: webdevops/php-nginx-dev:7.1
    volumes:
      - ./backend/app:/app/
      - ./backend/config/php.ini:/usr/local/etc/php/conf.d/php.ini
    command: /app/startup.sh
    ports:
      - '8080:80'
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - PHP_DEBUGGER=xdebug
      - APPLICTAION_UID=1000
      - APPLICTAION_GID=1000
      - JWT_SECRET=myawesomesecret
      - DATABASE_HOST=database:3306
      - DATABASE_USER=api
      - DATABASE_PASSWORD=api
      - DATABASE_SCHEMA=webshop

#node angular
  frontend:
    depends_on:
      - backend
    container_name: app-server
    image: node:alpine
    working_dir: /app
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/webshop-app:/app
    command: /app/startup.sh

#nginx proxy
  gateway:
    depends_on:
      - frontend
    container_name: reverse-proxy
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./rev-proxy/certs:/certs
      - ./rev-proxy/config:/etc/nginx/conf.d

#mysql server
  database:
    container_name: database-server
    image: mariadb:10.3
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=webshop
      - MYSQL_USER=api
      - MYSQL_PASSWORD=api

