
###
POST https://api.webshop.at/coupon/
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
    "value": "100.00",
    "expiration_date": "2018-06-10 23:59:59"
}

> {%
    client.test("Request successful", function() {
        client.assert(response.status === 201, "Could not create new coupon")
    });

    //client.assert(false, JSON.stringify(response.body));
    client.global.set("last_coupon", response.body.success.id);
    client.global.set("code", response.body.success.code);
%}

###

GET https://api.webshop.at/coupon/17
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer {{admin_token}}

> {%
    client.test("Request successful", function() {
      client.assert(response.status === 200, "Cloud not get coupon");
    });
 %}
###

PUT https://api.webshop.at/coupon/{{code}}/redeem/1
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer {{user_token}}

> {% client.assert(response.status === 204, "Unable to redeem token"); %}
###


