###
POST https://api.webshop.at/order/
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer {{user_token}}

{
    "user_id": 1,
    "payment_id": 7,
    "coupon_id": null,
    "products": [
        {
            "id": 14,
            "count": 4
        },{
            "id": 12,
            "count": 2
        },{
             "id": 11,
             "count": 1
         }
    ]
}

###

GET https://api.webshop.at/invoice/7
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer {{user_token}}

###

GET https://api.webshop.at/user/1/invoice/
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer {{user_token}}

###