

POST https://api.webshop.at/user/1/paymentMethod
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer {{user_token}}

{
    "paymentMethod": {
        "id": 1,
        "method": "VISA 123490439032"
    }
}

###

GET https://api.webshop.at/user/1/paymentMethod
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer {{user_token}}

> {% client.global.set('last_paymentMethod', response.body.success.paymentMethods[0].id); %}

###

DELETE https://api.webshop.at/user/1/paymentMethod/{{last_paymentMethod}}
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer {{user_token}}

###
