
POST https://api.webshop.at/product/
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
    "name": "Choco Suprise",
    "price": "3.99",
    "imageData":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkBAMAAACCzIhnAAAAG1BMVEXMzMyWlpacnJy+vr6jo6PFxcW3t7eqqqqxsbHbm8QuAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAiklEQVRYhe3QMQ6EIBAF0C+GSInF9mYTs+1ewRsQbmBlayysKefYO2asXbbYxvxHQj6ECQMAEREREf2NQ/fCtp5Zky6vtRMkSJEzhyISynWJnzH6Z8oQlzS7lEc/fLmmQUSvc16OrCPqRl1JePxQYo1ZSWVj9nxrrOb5esw+eXdvzTWfTERERHRXH4tWFZGswQ2yAAAAAElFTkSuQmCC",
    "rating": "4",
    "categories": [2]
}
> {%
    client.global.set('last_product', response.body.success.id);
%}
###


GET https://api.webshop.at/product/{{last_product}}
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer {{anonymous_token}}

> {%
    client.global.set('last_product_name', response.body.success.name);
    client.global.set('last_product_price', response.body.success.price);
    client.global.set('last_product_imagePath', response.body.success.imagePath);
    client.global.set('last_product_rating', response.body.success.rating);
%}

###

PUT https://api.webshop.at/product/{{last_product}}
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
    "name": "updated müsli",
    "price": "0.0",
    "imageData": null,
    "rating": "1",
    "categories": [2,3]
}

###

DELETE https://api.webshop.at/product/{{last_product}}
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer {{admin_token}}

###

GET https://api.webshop.at/product/category/1?search=mü
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer {{anonymous_token}}

###