# get anonymous token
POST https://api.webshop.at/token
Accept: application/json
Cache-Control: no-cache

> {%
    client.assert(response.status === 201, "Token creation failed");
    client.global.set('anonymous_token', response.body.token);
%}

### get user token
POST https://api.webshop.at/token
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

{
    "username": "if17b094",
    "password": "Hellokitty1"
}

> {%
    client.assert(response.status === 201, "Token creation failed");
    client.global.set('user_token', response.body.token);
%}

### get user token
POST https://api.webshop.at/token
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

{
    "username": "admin",
    "password": "Admin1"
}
> {%
    client.assert(response.status === 201, "Token creation failed");
    client.global.set('admin_token', response.body.token);
%}
###

### get another user token
POST https://api.webshop.at/token
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

{
    "username": "test",
    "password": "Test1"
}

> {%
    client.assert(response.status === 201, "Token creation failed");
    client.global.set('user_token', response.body.token);
%}

###